apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prod
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              files:
                - path: ./apps/*/config.yaml
              repoURL: https://github.com/dzibma/argocd-demo
              revision: main
          - list:
              elements: []
              elementsYaml: '{{ (empty .components) | ternary "[{}]" (.components | toJson) }}'
  goTemplate: true
  template:
    metadata:
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      name: 'prod-{{ printf "%s-%s" .path.basename .name }}'
      labels:
        app.kubernetes.io/instance: prod
    spec:
      destination:
        namespace: '{{ .namespace | default .path.basename }}'
        server: '{{ .cluster }}'
      project: default
      sources:
        - chart: '{{ .chart }}'
          helm:
            valueFiles:
              - '$values/values.yaml'
              - '$values/{{ .path.path }}/{{ .values | default (printf "values/%s.yaml" .name) }}'
          repoURL: '{{ .repository }}'
          targetRevision: '{{ .version }}'
        - ref: values
          repoURL: https://github.com/dzibma/argocd-demo
          targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
