apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/dzibma/argocd-demo
          revision: main
          files:
          - path: ./*/config.yaml
      - list:
          elements: []
          elementsYaml: "{{ .apps | toJson }}"
  template:
    metadata:
      name: '{{ .name }}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
      destination:
        server: '{{ .cluster }}'
        namespace: '{{ .namespace }}'
      sources:
        - repoURL: '{{ .repository }}'
          chart: '{{ .chart }}'
          targetRevision: '{{ .version }}'
          helm:
            valueFiles:
              - $values/{{ .path.path }}/{{ default "values.yaml" .valueFile }}
        - repoURL: https://github.com/dzibma/argocd-demo
          targetRevision: main
          ref: values
