{{- $name := (.Release.Name | trunc 63 | trimSuffix "-") -}}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ $name }}
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              files:
                - path: ./apps/*/config.yaml
              repoURL: https://github.com/dzibma/argocd-demo
              revision: main
          - list:
              elements: []
              elementsYaml: '{{`{{ .apps | toJson }}`}}'
  goTemplate: true
  template:
    metadata:
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      name: '{{ $name }}-{{`{{ .name }}`}}'
    spec:
      destination:
        namespace: '{{ $name }}-{{`{{ .namespace }}`}}'
        server: '{{`{{ .cluster }}`}}'
      project: default
      sources:
        - chart: '{{`{{ .chart }}`}}'
          helm:
            valueFiles:
              - '{{`$values/{{ .path.path }}/{{ default "values.yaml" .valueFile }}`}}'
          repoURL: '{{`{{ .repository }}`}}'
          targetRevision: '{{`{{ .version }}`}}'
        - ref: values
          repoURL: https://github.com/dzibma/argocd-demo
          targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
