repository: registry-1.docker.io/bitnamicharts
chart: nginx
version: 15.0.1

namespace: bar

destinations:
  - cluster: https://kubernetes.default.svc
    name: bar-sk
  - cluster: https://kubernetes.default.svc
    name: bar-bg
