repository: registry-1.docker.io/bitnamicharts
chart: nginx
version: 15.0.1

namespace: k3w

apps:
  - name: k3w-cz
    cluster: https://kubernetes.default.svc
    valueFile: values/cz.yaml
  - name: k3w-sk
    cluster: https://kubernetes.default.svc
    valueFile: values/sk.yaml
